[project]
name = "ML-Beans-Yuksel-Somers"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.7",
    "pandas>=2.3.3",
    "scikit-learn>=1.7.2",
    "ucimlrepo>=0.0.7",
]

